version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3308:3306"
    networks:
      - demo-network
  server:
    depends_on:
      - db
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: api-server
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - demo-network
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    expose:
      - 8080
  client:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - demo-network
    env_file:
      - ./frontend/.env
    expose:
      - 3000
networks:
  demo-network:
    driver: bridge
